simple_social.1/posts/urls.py
from django. urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name = 'all'),
    path('new/', views.CreatePost.as_view(), name = 'create'),
    path('by/<username>/', views.UserPosts.as_view(), name = 'for_user'),
    path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name = 'single'),
    path('by/<username>/<int:pk>/comments/', views.PostCommentDetails.as_view(), name = 'single_comments'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name = 'delete'),
    path('edit/<int:pk>/', views.UpdatePost.as_view(), name = 'edit'),
    path('comment/to/post/<int:pk>/', views.add_comment_to_post, name = 'comment'),
    path('comment/edit/<int:pk>/', views.edit_comment, name = 'edit_comment'),
    path('comment/approve/<int:pk>/', views.approve_comment, name = 'approve_comment'),
    path('comment/delete/<int:pk>', views.delete_comment, name = 'delete_comment'),
]

simple_social.1/simple_social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name = 'home'),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name = 'test'),
    path('thanks/', views.ThanksPage.as_view(), name = 'thanks'),
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('groups/', include('groups.urls', namespace = 'groups')),
    path('admin/', admin.site.urls),
]

simple_social.1/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model
from django.utils import timezone

import misaka

from groups.models import Group

User = get_user_model()

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, related_name = 'posts', on_delete = models.CASCADE)
    created_date = models.DateTimeField(auto_now = True)
    message = models.TextField()
    message_html = models.TextField(editable = False)
    group = models.ForeignKey(Group, related_name = 'posts', on_delete = models.CASCADE, null = True, blank = True)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs = {'pk': self.pk, 'username': self.user.username})
    
    class Meta:
        ordering = ['-created_date']
        unique_together = ['user', 'message']

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name = 'comments', on_delete = models.CASCADE)
    author = models.CharField(max_length = 256)
    text = models.TextField()
    created_at = models.DateTimeField(default = timezone.now)
    approved_comment = models.BooleanField(default = False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('post_list')

    def __str__(self):
        return self.text

simple_social.1/posts/forms.py
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

simple_social.1/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views import generic
from django.http import Http404
from django.contrib.auth import get_user_model

from braces.views import SelectRelatedMixin

from . import models, forms

User = get_user_model()

# Create your views here.
class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact = self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context
    
class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact = self.kwargs.get('username'))

class PostCommentDetails(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    template_name = 'posts/post_comment_detail.html'
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact = self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('message', 'group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit = False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class UpdatePost(LoginRequiredMixin,SelectRelatedMixin, generic.UpdateView):
    model = models.Post
    select_related = ('user', 'group')
    fields = ('message', 'group')

class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__id = self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(models.Post, pk = pk)
    if request.method == 'POST':
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.post = post
            comment.author = request.user.username
            comment.save()
            return redirect('posts:single_comments', username = post.user.username, pk = post.pk)
        else:
            print(form.errors)
    else:
        form = forms.CommentForm()
    return render(request, 'posts/comment_form.html', {'form': form})

@login_required
def edit_comment(request, pk):
    comment = get_object_or_404(models.Comment, pk = pk)
    form = forms.CommentForm(instance = comment)
    if request.method == 'POST':
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            # comment.author = form.cleaned_data['author']
            comment.text = form.cleaned_data['text']
            comment.save()
            return redirect('posts:single_comments', username = comment.post.user.username, pk = comment.post.pk)
        else:
            print(form.errors)
    return render(request, 'posts/comment_form.html', {'form': form})

@login_required
def approve_comment(request, pk):
    comment = get_object_or_404(models.Comment, pk = pk)
    comment.approve()
    return redirect('posts:single_comments', username = comment.post.user.username, pk = comment.post.pk)

@login_required
def delete_comment(request, pk):
    comment = get_object_or_404(models.Comment, pk = pk)
    post_pk = comment.post.pk
    post_username = comment.post.user.username
    comment.delete()
    return redirect('posts:single_comments', username = post_username, pk = post_pk)

simple_social.1/posts/templates/posts/_post.html
<div class="post media">
    <h3><a href="{% url 'posts:single_comments' username=post.user.username pk=post.pk %}">{{ post.message_html | safe }}</a></h3>
    <h5>Comments: {{ post.comments.count }}</h5>
    <div class="media-body">
        <!-- <strong>{{ post.user.username }}</strong> -->
        <h5 class="media-heading">
            <span class="username">
                <a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a>
            </span>
            <time class="time">
                <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_date }}</a>
            </time>
        </h5>
        <div class="media-footer">
            {% if user.is_authenticated and post.user == user %}
                <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
                    <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                    <span class="text-danger icon-label">Delete</span>
                </a>
                <a href="{% url 'posts:edit' pk=post.pk %}" title="edit" class="btn btn-simple">
                    <span class="glyphicon glyphicon-pencil text-warning" aria-hidden="true"></span>
                    <span class="text-warning icon-label">Edit</span>
                </a>
            {% endif %}
        </div>
    </div>
</div>

simple_social.1/posts/templates/posts/comment_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap3 %}
{% block post_content %}
<div class="container">
    {% if form.instance.pk %}
        <h1>Update Comment:</h1>
    {% else %}
        <h1>Edit Comment:</h1>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Post Comment">
    </form>
</div>
{% endblock %}

simple_social.1/posts/templates/posts/post_base.html
{% extends 'base.html' %}
{% block title_block %}<title>Posts</title>{% endblock %}
{% block content %}
    <div class="posts-page">
        <div class="container">
            <div class="row">
                {% block prepost %}{% endblock %}
                {% block post_content %}{% endblock %}
                {% block postpost %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

simple_social.1/posts/templates/posts/post_comment_detail.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
    <div class="container">
        <h1 class="postcontent">{{ post.message | safe | linebreaks }}</h1>
        <h4><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></h4>
    </div>
</div>
<hr>
<div class="container">
    <a href="{% url 'posts:comment' pk=post.pk %}" class="btn btn-primary btn-comment">Add Comment</a>
    <div class="col-md-8">
    {% for comment in post.comments.all %}
        {% if user.is_authenticated or comment.approved_comment %}
            <h6>Created: {{ comment.created_at }}</h6>
            {% if not comment.approved_comment %}
                {% if comment.author == user.username %}
                    <a href="{% url 'posts:edit_comment' pk=comment.pk %}" class="btn btn-warning"><span
                        class="glyphicon glyphicon-pencil"></span></a>
                {% else %}
                    <a href="{% url 'posts:approve_comment' pk=comment.pk %}" class="btn btn-success"><span
                        class="glyphicon glyphicon-ok"></span></a>
                {% endif %}
                <a href="{% url 'posts:delete_comment' pk=comment.pk %}" class="btn btn-danger"><span
                    class="glyphicon glyphicon-remove"></span></a>
            {% endif %}
            <h4>{{ comment.text | safe | linebreaks }}</h4>
            <u><p>Posted by: <a href="{% url 'posts:for_user' username=comment.author %}"><b>@{{ comment.author }}</b></a></p></u>
            <hr>
        {% endif %}
        {% empty %}
            <h6>No Comments</h6>
    {% endfor %}
    </div>
{% endblock %}

simple_social.1/posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
    <h3>Are you sure you want to delete this post?</h3>
    <div class="posts">
        {% include 'posts/_post.html' with post=object hide_delete=True %}
    </div>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
        <a class="btn btn-simple btn-large btn-default" href="{% url 'posts:single' username=user.username pk=object.pk %}">Cancel</a>
    </form>
{% endblock %}

simple_social.1/posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
    <div class="col-md-8">
        {% include 'posts/_post.html' %}
    </div>
{% endblock %}

simple_social.1/posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap3 %}
{% block post_content %}
    {% if form.instance.pk %}
        <h2>Update Post:</h2>
    {% else %}
        <h2>Create a new post:</h2>
    {% endif %}
    <form method="POST" id="postForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary btn-large" value="Post">
    </form>
{% endblock %}

simple_social.1/posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}
{% block prepost %}
    <div class="col-md-4">
        {% if user.is_authenticated %}
            <div class="card card-with-shadow">
                <div class="content">
                    <h5 class="title">Your Groups:</h5>
                    <ul class="list-unstyled">
                        {% for member_group in get_user_groups %}
                            <li class="group li-with-bullet">
                                <a href="{% url 'groups:single' slug=member_group.group.slug %}"></a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
        <div class="card card-with-shadow">
            <div class="content">
                <h5 class="title">All Groups</h5>
                <ul class="list-unstyled">
                    {% for other_group in get_other_groups %}
                        <li class="group li-with-bullet">
                            <a href="{% url 'groups:single' slug=other_group.slug %}"></a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}
{% block post_content %}
    <div class="col-md-8">
        {% for post in post_list %}
            {% include 'posts/_post.html' %}
        {% endfor %}
    </div>
{% endblock %}

simple_social.1/posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}
{% block prepost %}
    <div class="col-md-4">
        <h1>@{{ post_user.username }}</h1>
    </div>
{% endblock %}
{% block post_content %}
    <div class="col-md-8">
        {% for post in post_list %}
            {% include 'posts/_post.html' %}
        {% endfor %}
    </div>
{% endblock %}