simple_social.1/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroup.as_view(), name = 'all'),
    path('new/', views.CreateGroup.as_view(), name = 'create'),
    path('edit/<slug:slug>/', views.UpdateGroup.as_view(), name = 'edit'),
    path('posts/in/<slug:slug>/', views.SingleGroup.as_view(), name = 'single'),
    path('join/<slug:slug>/', views.JoinGroup.as_view(), name = 'join'),
    path('leave/<slug:slug>/', views.LeaveGroup.as_view(), name = 'leave'),
    path('delete/<slug:slug>/', views.DeleteGroup.as_view(), name = 'delete')
]

simple_social.1/posts/urls.py
from django. urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name = 'all'),
    path('new/', views.CreatePost.as_view(), name = 'create'),
    path('by/<username>/', views.UserPosts.as_view(), name = 'for_user'),
    path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name = 'single'),
    path('by/<username>/<int:pk>/comments/', views.PostCommentDetails.as_view(), name = 'single_comments'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name = 'delete'),
    path('edit/<int:pk>/', views.UpdatePost.as_view(), name = 'edit'),
    path('comment/to/post/<int:pk>/', views.add_comment_to_post, name = 'comment'),
    path('comment/edit/<int:pk>/', views.edit_comment, name = 'edit_comment'),
    path('comment/approve/<int:pk>/', views.approve_comment, name = 'approve_comment'),
    path('comment/delete/<int:pk>', views.delete_comment, name = 'delete_comment'),
]

simple_social.1/simple_social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name = 'home'),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name = 'test'),
    path('thanks/', views.ThanksPage.as_view(), name = 'thanks'),
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('groups/', include('groups.urls', namespace = 'groups')),
    path('admin/', admin.site.urls),
]

simple_social.1/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django import template
from django.urls import reverse

import misaka

User = get_user_model() # call things of current user session
register = template.Library() # custom template tag

# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length = 256, unique = True)
    slug = models.SlugField(allow_unicode = True, unique = True)
    description = models.TextField(blank = True, default = '')
    description_html = models.TextField(editable = False, default = '', blank = True)
    members = models.ManyToManyField(User, through = 'GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name = 'memberships', on_delete = models.CASCADE)
    user = models.ForeignKey(User, related_name = 'user_groups', on_delete = models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

simple_social.1/groups/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views import generic

from braces.views import SelectRelatedMixin

from .models import Group, GroupMember

# Create your views here.
class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group

class UpdateGroup(LoginRequiredMixin, generic.UpdateView):
    fields = ('name', 'description')
    model = Group

    def form_valid(self, form):
        self.object = form.save(commit = False)
        GroupMember.objects.filter(group = self.object).delete()
        membership = GroupMember()
        membership.group = self.object
        membership.user = self.request.user
        membership.save()
        return super().form_valid(form)

class SingleGroup(generic.DetailView):
    model = Group

class ListGroup(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin,  generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs = {'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug = self.kwargs.get('slug'))
        try:
            GroupMember.objects.create(user = self.request.user, group = group)
        except:
            messages.warning(self.request, 'Warning! already a member')
        else:
            messages.success(self.request, 'You are now a member!')
        return super().get(request, *args, **kwargs)

class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs = {'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(user = self.request.user, group__slug = self.kwargs.get('slug')).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry you are not in this group!')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group!')
        return super().get(request, *args, **kwargs)

class DeleteGroup(LoginRequiredMixin, generic.DeleteView):
    model = Group
    success_url = reverse_lazy('groups:all')

simple_social.1/groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block title_block %}<title>Group</title>{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            {% block pregroup %}{% endblock %}
            {% block group_content %}{% endblock %}
            {% block postgroup %}{% endblock %}
        </div>
    </div>
{% endblock %}

simple_social.1/groups/templates/groups/group_confirm_delete.html
{% extends 'groups/group_base.html' %}
{% block group_content %}
    {% if user.username.lower == 'arkajit' %}
        <h3>Are you sure you want to delete the group: {{ group.name }}?</h3>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
            <a class="btn btn-simple btn-large btn-default" href="{% url 'groups:single' slug=group.slug %}">Cancel</a>
        </form>
    {% else %}
        <h3>Sorry! Only the Admin is responsible for deleting groups.</h3>
    {% endif %}
{% endblock %}

simple_social.1/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}
{% block pregroup %}
    <h1>{{ group.name }}</h1>
    <h2>Member count: {{ group.members.count }}</h2>
    <div class="content">
        {% if user in group.members.all %}
            <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span>Leave</a>
        {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span>Join</a>
        {% endif %}
        <a href="{% url 'groups:edit' slug=group.slug %}" class="btn btn-lg btn-fill btn-success"><span class="glyphicon glyphicon-pencil"></span> Edit Group</a>
        <a href="{% url 'groups:delete' slug=group.slug %}" class="btn btn-lg btn-fill btn-danger"><span class="glyphicon glyphicon-remove"></span> Delete Group</a>
    </div>
{% endblock %}
{% block group_content %}
    <div class="col-md-8">
        {% if group.posts.count == 0 %}
            <h2>No posts in this group yet!</h2>
        {% else %}
            {% for post in group.posts.all %}
                {% include "posts/_post.html" %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

simple_social.1/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap3 %}
{% block content %}
    <div class="container">
        {% if form.instance.pk %}
            <h2>Update Group:</h2>
        {% else %}
            <h2>Create a new group:</h2>
        {% endif %}
        <form method="POST" id="groupForm">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary btn-large" value="Create">
        </form>
    </div>
{% endblock %}

simple_social.1/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
    <div class="col-md-4">
        <div class="content">
            {% if user.is_authenticated %}
                <h2>Welcome Back!</h2>
                <a href="{% url 'posts:for_user' username=user.username %}">@{{ user.username }}</a>
            {% endif %}
            <h2>Groups</h2>
            <p>Welcome to the groups page</p>
        </div>
        {% if user.is_authenticated %}
            <a href="{% url 'groups:create' %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"> Create New Group</span></a>
        {% endif %}
    </div>
{% endblock %}
{% block group_content %}
    <div class="col-md-8">
        <div class="list-group">
            {% for group in object_list %}
                <a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item">
                    <h3 class="title list-group-item-heading">{{ group.name }}</h3>
                    <div class="list-group-item-text container-fluid">
                        {{ group.description | safe }}
                        <div class="row">
                            <div class="col-md-4">
                                <span class="badge">
                                    {{ group.members.count }}
                                    member{{ group.members.count | pluralize }}
                                </span>
                            </div>
                            <div class="col-md-4">
                                <span class="badge">
                                    {{ group.posts.count }}
                                    post{{ group.posts.count | pluralize }}
                                </span>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}